a = int(input("Enter 1st integer :"))
b = int(input("Enter 2nd integer :"))
print(a+b  , "Addition")
print(a-b  , "Subtraction")
print(a*b  , "Multiplication")
print(a/b  , "Division")
print(a%b  , "Modulus")
print(a**b  , "Power")
print(a//b  , "floor division")
